[LIF_neuron_parameters]
beta = 0.9375
reset_potential = 0.0
resting_potential = 0.0
threshold = 1.0

[accuracy]
target_file = 'simulation/targets.txt'

[hidden_layers]
neurons = [128]

[input_layer]
input_length = 784

[input_spike_train]
batch_size = 256
filename = 'simulation/inputSpikes.txt'
spike_length = 100

[output_layer]
neurons = 10

[weight_files]
extra_weights = [
    'simulation/parameters/weightsFile1.txt',
    'simulation/parameters/weightsFile2.txt',
]
